# Build: 1 (bump this up by 1 to force an appveyor run)

os: Visual Studio 2015

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_compiler.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    # 32 bits

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    # 64 bits

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    # Also build on a Python version not pre-installed by Appveyor.
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10
    # - PYTHON: "C:\\Python266"
    #   PYTHON_VERSION: "2.6.6"
    #   PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell .ci\\appveyor\\install.ps1"
  # - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip --version"
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip install --upgrade --user setuptools pip"
  - "%WITH_COMPILER% %PYTHON%/python.exe scripts/winmake.py setup-dev-env"
  - "%WITH_COMPILER% %PYTHON%/python.exe -m pip freeze"
  - "%WITH_COMPILER% %PYTHON%/python.exe scripts/winmake.py install"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python.exe scripts/winmake.py test"

artifacts:
  - path: dist\*

cache:
  - '%LOCALAPPDATA%\pip\Cache'

skip_commits:
  message: skip-ci
